#!/bin/bash

cd Licensed_packages
mv targetp-2.0.Linux.tar.gz ../Dockerfiles/TargetP2.0 || echo "Failed to find TargetP-2.0 package, the tar.gz must be downloaded separately from DTU and and placed in changeloc/Licensed_packages"
mv signalp-6.0h.fast.tar.gz ../Dockerfiles/SignalP6.0 || echo "Failed to find SignalP-6.0 package, the tar.gz must be downloaded separately from DTU and and placed in changeloc/Licensed_packages"
mv deeploc-2.0.All.tar.gz ../Dockerfiles/Deeploc2.0 || echo "Failed to find Deeplox-2.0 package, the tar.gz must be downloaded separately from DTU and and placed in changeloc/Licensed_packages"

cd ../Dockerfiles/Deeploc2.0
echo "Building Deeploc 2, this may take some time ..."
docker build -t deeploc2 . || echo "Building Deeploc 2 failed, ensure tar.gz was in correct folder and copied across"

cd ../Mitofates
echo "Building Mitofates"
docker build -t mitofates . || echo "Building Mitofates failed"

cd ../SignalP6.0
echo "Building SignalP 6.0"
docker build -t signalp6 . || echo "Building SignalP 6.0 failed"

cd ../TargetP2.0
echo "Building TargetP 2.0"
docker build -t targetp2 . || echo "Building TargetP 2.0 failed"

cd ../TPpred3.0
echo "Building TPpred 3.0"
docker build -t tppred3 . || echo "Building TPpred 3.0 failed"

cd ../WolfPsort
echo "Building WoLFPsort"
docker build -t wolfpsort . || echo "Building WoLFPsort failed"

cd ../R
echo "Building Changeloc-R"
docker build -t changeloc/r . || echo "Building Changeloc-R failed"

cd ../Python
echo "Building Changeloc-Python"
docker build -t changeloc/python . || echo "Building Changeloc-Python failed"

# cd ../
# docker build .
