#!/bin/bash

cd Licensed_packages
mv targetp-2.0.Linux.tar.gz ../Dockerfiles/TargetP2.0 || echo "Failed to find TargetP-2.0 package, the tar.gz must be downloaded separately from DTU and and placed in changeloc/Licensed_packages"
mv signalp-6.0h.fast.tar.gz ../Dockerfiles/SignalP6.0 || echo "Failed to find SignalP-6.0 package, the tar.gz must be downloaded separately from DTU and and placed in changeloc/Licensed_packages"
mv deeploc-2.0.All.tar.gz ../Dockerfiles/Deeploc2.0 || echo "Failed to find Deeplox-2.0 package, the tar.gz must be downloaded separately from DTU and and placed in changeloc/Licensed_packages"

cd ../Dockerfiles/Deeploc2.0
echo "Building Deeploc 2, this may take some time ..."
docker build -t deeploc2 . 

cd ../Mitofates
docker build -t mitofates .

cd ../SignalP6.0
docker build -t signalp6 .

cd ../TargetP2.0
docker build -t targetp2 .

cd ../TPpred3.0
docker build -t tppred3 .

cd ../WolfPsort
docker build -t wolfpsort .

cd ../R
docker build -t changeloc/r .

# cd ../
# docker build .